### ISSUE TITLE
1.2.3以后无法识别实体枚举

### ISSUE THREAD

**Issue by jdonee** [abel533/mapper-boot-starter#11]
错误如下：
tk.mybatis.mapper.MapperException: 当前实体类不包含名为creditType的属性!
	at tk.mybatis.mapper.entity.Example$GeneratedCriteria.column(Example.java:302)
	at tk.mybatis.mapper.entity.Example$GeneratedCriteria.andIn(Example.java:435)
	at tk.mybatis.mapper.entity.Example$Criteria.andIn(Example.java:723)
        at com.rivers.domain.mysql.commonservice.credit.CCreditBackServiceImpl.hasCredit(CCreditBackServiceImpl.java:156)

源代码：
@Override
	public Boolean hasCredit(String shopkeeperId) {
		Example example = new Example(CreditBack.class);
		Criteria criteria = example.createCriteria();
		criteria.andEqualTo("shopkeeperId", shopkeeperId);
		criteria.andIn("creditType", Lists.newArrayList(CreditType.NO_CREDIT,CreditType.PART_CREDIT));//是否有未还款和部分还款
		int result=mapper.selectCountByExample(example);
		return result>0;
	}

@Table(name = "r_credit_back")
@Data
@EqualsAndHashCode(callSuper = false)
@NoArgsConstructor(force = true)
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@Builder
public class CreditBack extends BaseEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	// 还款状态
	private CreditType creditType;
        。。。。。。
}

**Comment by abel533** [comment]
看这里：
https://github.com/abel533/Mapper/blob/master/wiki/Changelog.md#2-350-%E7%89%88%E6%9C%AC%E4%B8%AD%E7%9A%84%E5%8F%82%E6%95%B0-annotationassimpletype-%E5%90%8D%E5%AD%97%E9%94%99%E4%BA%86%E7%8E%B0%E5%9C%A8%E6%94%B9%E4%B8%BA-enumassimpletype%E7%94%A8%E4%BA%8E%E9%85%8D%E7%BD%AE%E6%98%AF%E5%90%A6%E5%B0%86%E6%9E%9A%E4%B8%BE%E7%B1%BB%E5%9E%8B%E5%BD%93%E6%88%90%E5%9F%BA%E6%9C%AC%E7%B1%BB%E5%9E%8B%E5%AF%B9%E5%BE%85

**Comment by liangxm** [comment]
这个地址不能访问了！
