### ISSUE TITLE
更新1.2.0后selectByCondition查询报错

### ISSUE THREAD

**Issue by yangdq1** [abel533/mapper-boot-starter#6]
更新1.2.0后Condition查询报错，MapperScan 替换了，mybatis 官方 starter也去掉了，
还是报错，是不是我哪里弄错了？
java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.ConditionProvider.<init>()

**Comment by abel533** [comment]
Mapper-Starer 1.2.0 使用须知
使用1.2.0的时候需要满足下面三种情况之一

1. 项目（间接）依赖中不包含官方的mybaitis-starter

2. 使用tk提供的@MapperScan注解方式

3. 在启动类上增加如下注解忽略

```java
@EnableAutoConfiguration(
   exclude={org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration.class})
public class Application {

}
```
